-- =====================================================================
-- 같이놀개 M1 목표 구조 참고 DDL / ERDCloud 참고용 (rev4)
-- 실제 적용 물리 스키마의 정본은 src/main/resources/db/migration Flyway 파일이다.
-- 이 파일을 직접 실행하지 않고 신규 구조를 다음 버전 Migration으로 분할한다.
-- 최신 제품 정책 기준. 실제 Flyway에서는 적용된 migration을 수정하지 않고
-- 다음 버전 migration으로 나누어 반영한다.
-- =====================================================================

CREATE TABLE neighborhoods (
    code               VARCHAR(20)  PRIMARY KEY,
    sido_name          VARCHAR(50)  NOT NULL,
    sigungu_name       VARCHAR(50),
    eupmyeondong_name  VARCHAR(50),
    active             BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE users (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email              VARCHAR(320) NOT NULL,
    password_hash      VARCHAR(255) NOT NULL,
    nickname           VARCHAR(30)  NOT NULL,
    public_tag         VARCHAR(30)  NOT NULL UNIQUE,
    role               VARCHAR(20)  NOT NULL DEFAULT 'USER',
    account_status     VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    neighborhood_code  VARCHAR(20)  NOT NULL REFERENCES neighborhoods(code),
    active_pet_id      BIGINT,
    version            BIGINT       NOT NULL DEFAULT 0,
    withdrawn_at       TIMESTAMPTZ,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_users_role
        CHECK (role IN ('USER', 'ADMIN', 'SUPER_ADMIN')),
    CONSTRAINT ck_users_status
        CHECK (account_status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN'))
);

CREATE UNIQUE INDEX uk_users_email_lower ON users (LOWER(email));

CREATE TABLE media_assets (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id  BIGINT       NOT NULL REFERENCES users(id),
    purpose        VARCHAR(20)  NOT NULL,
    status         VARCHAR(20)  NOT NULL,
    object_key     VARCHAR(512) NOT NULL UNIQUE,
    content_type   VARCHAR(100) NOT NULL,
    size_bytes     BIGINT       NOT NULL,
    expires_at     TIMESTAMPTZ  NOT NULL,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_media_size CHECK (size_bytes > 0),
    CONSTRAINT ck_media_status
        CHECK (status IN (
            'PENDING', 'UPLOADED', 'EXPIRED', 'DELETE_REQUESTED', 'DELETED'
        ))
);

CREATE TABLE pets (
    id                BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id     BIGINT        NOT NULL REFERENCES users(id),
    public_tag        VARCHAR(30)   NOT NULL UNIQUE,
    nickname          VARCHAR(30)   NOT NULL,
    breed_name        VARCHAR(100),
    sex               VARCHAR(10),
    neutered          BOOLEAN,
    birth_date        DATE,
    weight_kg         NUMERIC(5,2),
    size_code         VARCHAR(20),
    bio               VARCHAR(500),
    personality_tags  JSONB,
    care_note         VARCHAR(500),
    status            VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    profile_asset_id  BIGINT        REFERENCES media_assets(id),
    version           BIGINT        NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    deleted_at        TIMESTAMPTZ,
    CONSTRAINT ck_pets_nickname
        CHECK (LENGTH(BTRIM(nickname)) >= 1),
    CONSTRAINT ck_pets_public_tag_format
        CHECK (public_tag ~ '^.{1,25}#[A-Z0-9]{4}$'),
    CONSTRAINT ck_pets_status
        CHECK (status IN ('ACTIVE', 'SUSPENDED', 'DELETED')),
    CONSTRAINT ck_pets_status_deleted_at
        CHECK (
            (status = 'DELETED' AND deleted_at IS NOT NULL)
            OR
            (status IN ('ACTIVE', 'SUSPENDED') AND deleted_at IS NULL)
        )
);

CREATE INDEX ix_pets_owner_active_order
    ON pets (owner_user_id, created_at, id)
    WHERE deleted_at IS NULL;

ALTER TABLE users
    ADD CONSTRAINT fk_users_active_pet
    FOREIGN KEY (active_pet_id) REFERENCES pets(id);

CREATE TABLE refresh_tokens (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users(id),
    token_hash  VARCHAR(64)  NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ  NOT NULL,
    revoked_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE pet_registration_verification_attempts (
    id                                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requested_by_user_id                BIGINT       NOT NULL REFERENCES users(id),
    consumed_pet_id                     BIGINT       REFERENCES pets(id),
    token_hash                          VARCHAR(64),
    status                              VARCHAR(20)  NOT NULL,
    result_code                         VARCHAR(50)  NOT NULL,
    input_identifier_type               VARCHAR(30)  NOT NULL,
    input_identifier_fingerprint        VARCHAR(64),
    canonical_registration_fingerprint  VARCHAR(64),
    fingerprint_key_version             SMALLINT,
    provider                            VARCHAR(50),
    provider_reference                  VARCHAR(100),
    verified_pet_snapshot               JSONB,
    consent_version                     VARCHAR(30),
    consented_at                        TIMESTAMPTZ,
    expires_at                          TIMESTAMPTZ,
    consumed_at                         TIMESTAMPTZ,
    created_at                          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at                          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_pet_verification_attempt_status
        CHECK (status IN (
            'SUCCEEDED', 'REJECTED', 'FAILED', 'EXPIRED', 'CONSUMED'
        )),
    CONSTRAINT ck_pet_verification_attempt_consumed
        CHECK (
            (status = 'CONSUMED' AND consumed_pet_id IS NOT NULL AND consumed_at IS NOT NULL)
            OR (
                status <> 'CONSUMED'
                AND consumed_pet_id IS NULL
                AND consumed_at IS NULL
            )
        )
);

CREATE UNIQUE INDEX uk_pet_verification_attempt_token
    ON pet_registration_verification_attempts (token_hash)
    WHERE token_hash IS NOT NULL
      AND status = 'SUCCEEDED';

CREATE TABLE pet_registration_verifications (
    id                                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id                              BIGINT       NOT NULL UNIQUE REFERENCES pets(id),
    source_attempt_id                   BIGINT       NOT NULL UNIQUE REFERENCES pet_registration_verification_attempts(id),
    status                              VARCHAR(20)  NOT NULL,
    provider                            VARCHAR(50)  NOT NULL,
    provider_reference                  VARCHAR(100),
    canonical_registration_fingerprint  VARCHAR(64)  NOT NULL,
    fingerprint_key_version             SMALLINT     NOT NULL DEFAULT 1,
    verified_pet_snapshot               JSONB        NOT NULL,
    verified_at                         TIMESTAMPTZ  NOT NULL,
    revoked_at                          TIMESTAMPTZ,
    created_at                          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at                          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_pet_verification_status
        CHECK (status IN ('VERIFIED', 'REVOKED'))
);

CREATE UNIQUE INDEX uk_pet_verification_canonical
    ON pet_registration_verifications (canonical_registration_fingerprint)
    WHERE status = 'VERIFIED';

CREATE TABLE friend_requests (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_pet_id  BIGINT       NOT NULL REFERENCES pets(id),
    target_pet_id     BIGINT       NOT NULL REFERENCES pets(id),
    pair_low_id       BIGINT       GENERATED ALWAYS AS
        (LEAST(requester_pet_id, target_pet_id)) STORED,
    pair_high_id      BIGINT       GENERATED ALWAYS AS
        (GREATEST(requester_pet_id, target_pet_id)) STORED,
    status            VARCHAR(20)  NOT NULL,
    requested_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    responded_at      TIMESTAMPTZ,
    expires_at        TIMESTAMPTZ  NOT NULL,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_friend_request_self
        CHECK (requester_pet_id <> target_pet_id),
    CONSTRAINT ck_friend_request_status
        CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELED', 'EXPIRED'))
);

CREATE UNIQUE INDEX uk_friend_request_pending_pair
    ON friend_requests (pair_low_id, pair_high_id)
    WHERE status = 'PENDING';

CREATE INDEX ix_friend_request_pending_requester_target_expires
    ON friend_requests (requester_pet_id, target_pet_id, expires_at)
    WHERE status = 'PENDING';

CREATE INDEX ix_friend_request_pending_target_requester_expires
    ON friend_requests (target_pet_id, requester_pet_id, expires_at)
    WHERE status = 'PENDING';

CREATE TABLE friendships (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_low_id    BIGINT       NOT NULL REFERENCES pets(id),
    pet_high_id   BIGINT       NOT NULL REFERENCES pets(id),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_friendship_pair CHECK (pet_low_id < pet_high_id),
    CONSTRAINT uk_friendship_pair UNIQUE (pet_low_id, pet_high_id)
);

CREATE INDEX ix_friendship_pet_high_low
    ON friendships (pet_high_id, pet_low_id);

CREATE TABLE user_blocks (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_user_id   BIGINT       NOT NULL REFERENCES users(id),
    blocked_user_id   BIGINT       NOT NULL REFERENCES users(id),
    source_pet_id     BIGINT       REFERENCES pets(id),
    target_pet_id     BIGINT       REFERENCES pets(id),
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_user_block_self CHECK (blocker_user_id <> blocked_user_id),
    CONSTRAINT uk_user_block_pair UNIQUE (blocker_user_id, blocked_user_id)
);

CREATE INDEX ix_user_blocks_blocker_created
    ON user_blocks (blocker_user_id, created_at DESC, id DESC);

CREATE INDEX ix_user_blocks_blocked_user
    ON user_blocks (blocked_user_id);

CREATE TABLE chat_rooms (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type             VARCHAR(20)  NOT NULL DEFAULT 'DIRECT',
    status           VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    origin           VARCHAR(20)  NOT NULL,
    pet_low_id       BIGINT       REFERENCES pets(id),
    pet_high_id      BIGINT       REFERENCES pets(id),
    last_message_at  TIMESTAMPTZ,
    archived_at      TIMESTAMPTZ,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_chat_room_type CHECK (type IN ('DIRECT', 'GROUP')),
    CONSTRAINT ck_chat_room_status CHECK (status IN ('ACTIVE', 'ARCHIVED')),
    CONSTRAINT ck_chat_room_origin CHECK (origin IN ('GREETING', 'FRIEND')),
    CONSTRAINT ck_chat_room_direct_pair CHECK (
        (type = 'DIRECT' AND pet_low_id IS NOT NULL
            AND pet_high_id IS NOT NULL AND pet_low_id < pet_high_id)
        OR
        (type = 'GROUP' AND pet_low_id IS NULL AND pet_high_id IS NULL)
    )
);

CREATE UNIQUE INDEX uk_chat_room_direct_pair
    ON chat_rooms (pet_low_id, pet_high_id)
    WHERE type = 'DIRECT';

CREATE TABLE setlogs (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_pet_id         BIGINT       NOT NULL REFERENCES pets(id),
    media_asset_id        BIGINT       NOT NULL REFERENCES media_assets(id),
    caption               VARCHAR(500),
    status                VARCHAR(20)  NOT NULL DEFAULT 'VISIBLE',
    reaction_cute_count   INTEGER      NOT NULL DEFAULT 0,
    reaction_like_count   INTEGER      NOT NULL DEFAULT 0,
    is_seed               BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_setlog_status
        CHECK (status IN ('VISIBLE', 'DELETED_BY_AUTHOR')),
    CONSTRAINT ck_setlog_reaction_counts
        CHECK (reaction_cute_count >= 0 AND reaction_like_count >= 0)
);

CREATE TABLE greetings (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_pet_id   BIGINT       NOT NULL REFERENCES pets(id),
    to_pet_id     BIGINT       NOT NULL REFERENCES pets(id),
    setlog_id     BIGINT       NOT NULL REFERENCES setlogs(id),
    room_id       BIGINT       NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'SENT',
    responded_at  TIMESTAMPTZ,
    expires_at    TIMESTAMPTZ  NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_greeting_self CHECK (from_pet_id <> to_pet_id),
    CONSTRAINT ck_greeting_status CHECK (status IN ('SENT', 'RESPONDED', 'EXPIRED')),
    CONSTRAINT ck_greeting_response CHECK (
        (status = 'RESPONDED' AND responded_at IS NOT NULL)
        OR (status <> 'RESPONDED' AND responded_at IS NULL)
    ),
    CONSTRAINT uk_greeting_direction UNIQUE (from_pet_id, to_pet_id)
);

-- greetings.room_id는 무답 방 물리 삭제 후에도 이력을 남기기 위한
-- 식별자 스냅샷이다. 따라서 chat_rooms FK를 두지 않는다.

CREATE TABLE chat_room_participants (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id    BIGINT       NOT NULL REFERENCES chat_rooms(id) ON DELETE CASCADE,
    pet_id     BIGINT       NOT NULL REFERENCES pets(id),
    joined_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    left_at    TIMESTAMPTZ,
    CONSTRAINT uk_chat_participant UNIQUE (room_id, pet_id)
);

CREATE TABLE meeting_cards (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id          BIGINT       NOT NULL REFERENCES chat_rooms(id),
    creator_pet_id   BIGINT       NOT NULL REFERENCES pets(id),
    card_type        VARCHAR(20)  NOT NULL,
    place_text       VARCHAR(500) NOT NULL,
    meet_at          TIMESTAMPTZ  NOT NULL,
    status           VARCHAR(20)  NOT NULL DEFAULT 'OPEN',
    canceled_by_pet_id BIGINT     REFERENCES pets(id),
    canceled_at      TIMESTAMPTZ,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_meeting_card_type
        CHECK (card_type IN ('WALK', 'PLAY', 'HOSPITAL', 'OTHER')),
    CONSTRAINT ck_meeting_card_status CHECK (status IN ('OPEN', 'CANCELED')),
    CONSTRAINT ck_meeting_card_cancel CHECK (
        (status = 'CANCELED' AND canceled_by_pet_id IS NOT NULL AND canceled_at IS NOT NULL)
        OR (
            status = 'OPEN'
            AND canceled_by_pet_id IS NULL
            AND canceled_at IS NULL
        )
    )
);

CREATE TABLE chat_messages (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id            BIGINT       NOT NULL REFERENCES chat_rooms(id) ON DELETE CASCADE,
    sender_type        VARCHAR(20)  NOT NULL,
    sender_pet_id      BIGINT       REFERENCES pets(id),
    type               VARCHAR(20)  NOT NULL,
    body               VARCHAR(2000),
    meeting_card_id    BIGINT       REFERENCES meeting_cards(id),
    client_message_id  VARCHAR(64),
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_chat_message_sender CHECK (
        (sender_type = 'PET' AND sender_pet_id IS NOT NULL)
        OR (sender_type = 'SYSTEM' AND sender_pet_id IS NULL)
    ),
    CONSTRAINT ck_chat_message_type CHECK (type IN ('TEXT', 'CARD', 'SYSTEM')),
    CONSTRAINT ck_chat_message_payload CHECK (
        (type = 'TEXT' AND sender_type = 'PET'
            AND body IS NOT NULL AND BTRIM(body) <> '' AND meeting_card_id IS NULL)
        OR
        (type = 'CARD' AND sender_type = 'PET'
            AND body IS NULL AND meeting_card_id IS NOT NULL)
        OR
        (type = 'SYSTEM' AND sender_type = 'SYSTEM'
            AND body IS NOT NULL AND BTRIM(body) <> '' AND meeting_card_id IS NULL)
    ),
    CONSTRAINT uk_chat_message_client UNIQUE (room_id, client_message_id),
    CONSTRAINT uk_chat_message_card UNIQUE (meeting_card_id)
);

CREATE TABLE card_drafts (
    id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id              BIGINT       NOT NULL REFERENCES chat_rooms(id),
    requested_by_pet_id  BIGINT       NOT NULL REFERENCES pets(id),
    card_type            VARCHAR(20),
    place_text           VARCHAR(500),
    meet_at              TIMESTAMPTZ,
    fallback_reason      VARCHAR(30),
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_card_draft_type
        CHECK (card_type IS NULL OR card_type IN ('WALK', 'PLAY', 'HOSPITAL', 'OTHER')),
    CONSTRAINT ck_card_draft_fallback_reason
        CHECK (
            fallback_reason IS NULL
            OR fallback_reason IN ('TIMEOUT', 'MODEL_ERROR', 'INSUFFICIENT_CONTEXT')
        )
);

-- meeting_cards가 card_drafts보다 앞에 정의되어 있어 인라인 FK를 걸 수 없다.
-- 초안으로 확정한 카드를 역추적하고, 한 초안이 카드를 두 번 만들지 못하게 막는다.
ALTER TABLE meeting_cards
    ADD COLUMN source_draft_id BIGINT NULL REFERENCES card_drafts(id);

ALTER TABLE meeting_cards
    ADD CONSTRAINT uk_meeting_card_source_draft UNIQUE (source_draft_id);

CREATE TABLE meeting_participants (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_card_id  BIGINT       NOT NULL REFERENCES meeting_cards(id),
    pet_id           BIGINT       NOT NULL REFERENCES pets(id),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_meeting_participant UNIQUE (meeting_card_id, pet_id)
);

CREATE TABLE setlog_reactions (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setlog_id       BIGINT       NOT NULL REFERENCES setlogs(id),
    reactor_pet_id  BIGINT       NOT NULL REFERENCES pets(id),
    type            VARCHAR(20)  NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_setlog_reaction_type CHECK (type IN ('CUTE', 'LIKE')),
    CONSTRAINT uk_setlog_reaction UNIQUE (setlog_id, reactor_pet_id, type)
);

CREATE TABLE reports (
    id                    BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_user_id      BIGINT        NOT NULL REFERENCES users(id),
    reporter_pet_id       BIGINT        NOT NULL REFERENCES pets(id),
    reported_user_id      BIGINT        NOT NULL REFERENCES users(id),
    reported_pet_id       BIGINT        NOT NULL REFERENCES pets(id),
    room_id               BIGINT        NOT NULL REFERENCES chat_rooms(id),
    reason_code           VARCHAR(30)   NOT NULL,
    detail                VARCHAR(500),
    status                VARCHAR(20)   NOT NULL DEFAULT 'OPEN',
    reviewed_by_admin_id  BIGINT        REFERENCES users(id),
    reviewed_at           TIMESTAMPTZ,
    resolution_note       VARCHAR(500),
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_report_self CHECK (reporter_user_id <> reported_user_id),
    CONSTRAINT ck_report_reason
        CHECK (reason_code IN ('HARASSMENT', 'SPAM', 'OTHER')),
    CONSTRAINT ck_report_other_detail
        CHECK (
            reason_code <> 'OTHER'
            OR (detail IS NOT NULL AND btrim(detail) <> '')
        ),
    CONSTRAINT ck_report_status
        CHECK (status IN ('OPEN', 'ACTIONED', 'NO_ACTION'))
);

CREATE UNIQUE INDEX uk_reports_open_reporter_room
    ON reports (reporter_user_id, room_id)
    WHERE status = 'OPEN';

CREATE TABLE admin_actions (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_admin_id  BIGINT        NOT NULL REFERENCES users(id),
    target_type     VARCHAR(30)   NOT NULL,
    target_id       BIGINT        NOT NULL,
    action_type     VARCHAR(50)   NOT NULL,
    reason          VARCHAR(500)  NOT NULL,
    before_state    JSONB,
    after_state     JSONB,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_admin_action_type
        CHECK (action_type IN ('DISMISSED', 'WARNING'))
);

-- M2에서 별도 migration으로 추가:
-- Google OAuth, GPS 동네 확인, 사용자 셋로그 업로드,
-- 지도·장소, 만남 확인, 후기·발자국, 그룹 채팅, 대화 맥락 검열.
