spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: ${FLYWAY_ENABLED:false}
    locations:
      - classpath:db/migration

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  jwt:
    issuer: ${JWT_ISSUER}
    secret: ${JWT_SECRET}
    access-ttl: ${JWT_ACCESS_TTL}
    refresh-ttl: ${JWT_REFRESH_TTL}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  s3:
    bucket: ${S3_BUCKET}
    region: ${AWS_REGION}
    endpoint:
    presign-endpoint:
    path-style-access-enabled: false
