package itda.medicalsupport.service;
import itda.common.constants.ErrorCode; import itda.common.exception.BusinessException; import itda.medicalsupport.domain.*; import itda.medicalsupport.repository.*; import itda.user.domain.Role; import itda.user.repository.UserRepository; import java.util.*; import lombok.RequiredArgsConstructor; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor public class MedicalSupportReviewService {
 private final MedicalSupportRevisionRepository revisions; private final MedicalSupportProgramRepository programs; private final UserRepository users;
 // Lock order is Revision root row, then Program root row. Keep that order for verify/reject paths.
 @Transactional public MedicalSupportRevision verify(long adminId,long revisionId){requireAdmin(adminId); MedicalSupportRevision revision=revisions.findByIdForUpdate(revisionId).orElseThrow(()->new BusinessException(ErrorCode.MEDICAL_SUPPORT_REVISION_NOT_FOUND)); ensurePending(revision); if(revision.getProgramName()==null||revision.getProgramYear()==null||revision.getRegionCode()==null||revision.getRegionScope()==null)throw new BusinessException(ErrorCode.VALIDATION_FAILED); MedicalSupportProgram program=resolveProgram(revision); MedicalSupportRevision previous=program.getCurrentVerifiedRevision(); MedicalSupportChangeType change=previous==null?MedicalSupportChangeType.NEW:Objects.equals(previous.getSemanticFingerprint(),revision.getSemanticFingerprint())?MedicalSupportChangeType.UNCHANGED:MedicalSupportChangeType.UPDATED; revision.attach(program); revision.verify(adminId,change); if(previous==null||isNewer(revision,previous))program.apply(revision); return revision; }
 @Transactional public MedicalSupportRevision reject(long adminId,long revisionId,String reason){requireAdmin(adminId); MedicalSupportRevision revision=revisions.findByIdForUpdate(revisionId).orElseThrow(()->new BusinessException(ErrorCode.MEDICAL_SUPPORT_REVISION_NOT_FOUND)); ensurePending(revision); revision.reject(adminId,reason); return revision;}
 private MedicalSupportProgram resolveProgram(MedicalSupportRevision r){ Optional<MedicalSupportProgram> found=r.getStableSourceProgramId()!=null&&!r.getStableSourceProgramId().isBlank()?programs.findBySourceOrganizationAndStableSourceProgramId(r.getSourceOrganization(),r.getStableSourceProgramId()):programs.findBySourceOrganizationAndRegionScopeAndRegionCodeAndNormalizedProgramNameAndProgramYear(r.getSourceOrganization(),r.getRegionScope(),r.getRegionCode(),r.getNormalizedProgramName(),r.getProgramYear()); if(found.isPresent())return programs.findByIdForUpdate(found.get().getId()).orElseThrow(()->new BusinessException(ErrorCode.CONCURRENT_UPDATE_CONFLICT)); try{return programs.saveAndFlush(MedicalSupportProgram.from(r));}catch(DataIntegrityViolationException e){throw new BusinessException(ErrorCode.CONCURRENT_UPDATE_CONFLICT);} }
 private void ensurePending(MedicalSupportRevision r){if(r.getReviewStatus()!=MedicalSupportReviewStatus.PENDING_REVIEW)throw new BusinessException(ErrorCode.MEDICAL_SUPPORT_REVISION_ALREADY_CLOSED);} private void requireAdmin(long id){boolean ok=users.findById(id).map(u->u.isActive()&&(u.getRole()==Role.ADMIN||u.getRole()==Role.SUPER_ADMIN)).orElse(false);if(!ok)throw new BusinessException(ErrorCode.FORBIDDEN);}
 boolean isNewer(MedicalSupportRevision candidate,MedicalSupportRevision current){if(candidate.getSourcePublishedAt()!=null&&current.getSourcePublishedAt()!=null){int compared=candidate.getSourcePublishedAt().compareTo(current.getSourcePublishedAt());if(compared!=0)return compared>0;}int compared=candidate.getFetchedAt().compareTo(current.getFetchedAt());if(compared!=0)return compared>0;return candidate.getId()>current.getId();}
}
