CREATE TABLE reports (
    id                    BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_user_id      BIGINT        NOT NULL REFERENCES users(id),
    reporter_pet_id       BIGINT        NOT NULL REFERENCES pets(id),
    reported_user_id      BIGINT        NOT NULL REFERENCES users(id),
    reported_pet_id       BIGINT        NOT NULL REFERENCES pets(id),
    room_id               BIGINT        NOT NULL REFERENCES chat_rooms(id),
    reason_code           VARCHAR(30)   NOT NULL,
    detail                VARCHAR(500),
    status                VARCHAR(20)   NOT NULL DEFAULT 'OPEN',
    reviewed_by_admin_id  BIGINT        REFERENCES users(id),
    reviewed_at           TIMESTAMPTZ,
    resolution_note       VARCHAR(500),
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_report_self CHECK (reporter_user_id <> reported_user_id),
    CONSTRAINT ck_report_reason
        CHECK (reason_code IN ('HARASSMENT', 'SPAM', 'OTHER')),
    CONSTRAINT ck_report_other_detail
        CHECK (
            reason_code <> 'OTHER'
            OR (detail IS NOT NULL AND btrim(detail) <> '')
        ),
    CONSTRAINT ck_report_status
        CHECK (status IN ('OPEN', 'ACTIONED', 'NO_ACTION'))
);

CREATE UNIQUE INDEX uk_reports_open_reporter_room
    ON reports (reporter_user_id, room_id)
    WHERE status = 'OPEN';