CREATE TABLE user_blocks (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_user_id   BIGINT       NOT NULL,
    blocked_user_id   BIGINT       NOT NULL,
    source_pet_id     BIGINT       NULL,
    target_pet_id     BIGINT       NULL,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_user_blocks_blocker_user
        FOREIGN KEY (blocker_user_id) REFERENCES users (id),
    CONSTRAINT fk_user_blocks_blocked_user
        FOREIGN KEY (blocked_user_id) REFERENCES users (id),
    CONSTRAINT fk_user_blocks_source_pet
        FOREIGN KEY (source_pet_id) REFERENCES pets (id),
    CONSTRAINT fk_user_blocks_target_pet
        FOREIGN KEY (target_pet_id) REFERENCES pets (id),
    CONSTRAINT ck_user_blocks_self
        CHECK (blocker_user_id <> blocked_user_id),
    CONSTRAINT uk_user_block_pair
        UNIQUE (blocker_user_id, blocked_user_id)
);

CREATE INDEX ix_user_blocks_blocker_created
    ON user_blocks (blocker_user_id, created_at DESC, id DESC);

CREATE INDEX ix_user_blocks_blocked_user
    ON user_blocks (blocked_user_id);
