CREATE TABLE IF NOT EXISTS media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_type VARCHAR(20) NOT NULL,
    path VARCHAR(2000) NOT NULL,
    status VARCHAR(20) NOT NULL,
    user_id BIGINT,
    upload_id VARCHAR(500),
    file_size BIGINT,
    deleted_at TIMESTAMPTZ,
    attributes JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_media_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_media_path UNIQUE (path),
    CONSTRAINT ck_media_type
        CHECK (media_type IN ('IMAGE', 'VIDEO')),
    CONSTRAINT ck_media_status
        CHECK (status IN ('INIT', 'UPLOADED', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_media_file_size
        CHECK (file_size IS NULL OR file_size > 0)
);

CREATE INDEX ix_media_user_created
    ON media (user_id, created_at DESC);

CREATE TABLE setlogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_pet_id BIGINT NOT NULL,
    media_id BIGINT NOT NULL,
    caption VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'VISIBLE',
    reaction_cute_count INTEGER NOT NULL DEFAULT 0,
    reaction_like_count INTEGER NOT NULL DEFAULT 0,
    is_seed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_setlogs_author_pet
        FOREIGN KEY (author_pet_id) REFERENCES pets (id),
    CONSTRAINT fk_setlogs_media
        FOREIGN KEY (media_id) REFERENCES media (id),
    CONSTRAINT uk_setlogs_media UNIQUE (media_id),
    CONSTRAINT ck_setlogs_status
        CHECK (status IN ('VISIBLE', 'DELETED_BY_AUTHOR')),
    CONSTRAINT ck_setlogs_reaction_counts
        CHECK (
            reaction_cute_count >= 0
            AND reaction_like_count >= 0
        )
);

CREATE INDEX ix_setlogs_seed_visible_created
    ON setlogs (created_at, id)
    WHERE is_seed = TRUE AND status = 'VISIBLE';

CREATE TABLE setlog_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setlog_id BIGINT NOT NULL,
    reactor_pet_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_setlog_reactions_setlog
        FOREIGN KEY (setlog_id) REFERENCES setlogs (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_setlog_reactions_reactor_pet
        FOREIGN KEY (reactor_pet_id) REFERENCES pets (id),
    CONSTRAINT ck_setlog_reactions_type
        CHECK (type IN ('CUTE', 'LIKE')),
    CONSTRAINT uk_setlog_reactions
        UNIQUE (setlog_id, reactor_pet_id, type)
);

CREATE INDEX ix_setlog_reactions_reactor
    ON setlog_reactions (reactor_pet_id, setlog_id);
