CREATE TABLE greetings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_pet_id BIGINT NOT NULL,
    to_pet_id BIGINT NOT NULL,
    setlog_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'SENT',
    responded_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_greetings_from_pet
        FOREIGN KEY (from_pet_id) REFERENCES pets (id),
    CONSTRAINT fk_greetings_to_pet
        FOREIGN KEY (to_pet_id) REFERENCES pets (id),
    CONSTRAINT fk_greetings_setlog
        FOREIGN KEY (setlog_id) REFERENCES setlogs (id),
    CONSTRAINT ck_greetings_self
        CHECK (from_pet_id <> to_pet_id),
    CONSTRAINT ck_greetings_status
        CHECK (status IN ('SENT', 'RESPONDED', 'EXPIRED')),
    CONSTRAINT ck_greetings_response
        CHECK (
            (status = 'RESPONDED' AND responded_at IS NOT NULL)
            OR
            (status <> 'RESPONDED' AND responded_at IS NULL)
        ),
    CONSTRAINT uk_greetings_direction
        UNIQUE (from_pet_id, to_pet_id)
);

-- room_id is a snapshot. The Greeting history survives physical deletion
-- of an unanswered room, so this column intentionally has no room FK.
CREATE INDEX ix_greetings_room_status
    ON greetings (room_id, status);

CREATE INDEX ix_greetings_from_created
    ON greetings (from_pet_id, created_at);
