-- 약속 카드(M1-030).
-- card_drafts 를 먼저 만든다. meeting_cards.source_draft_id 가 이를 참조하므로
-- 순서를 바꾸면 forward reference 로 깨진다.

CREATE TABLE card_drafts (
    id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id              BIGINT       NOT NULL REFERENCES chat_rooms(id),
    requested_by_pet_id  BIGINT       NOT NULL REFERENCES pets(id),
    card_type            VARCHAR(20),
    place_text           VARCHAR(500),
    meet_at              TIMESTAMPTZ,
    fallback_reason      VARCHAR(30),
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- AI 가 종류를 못 뽑으면 null 로 남고 사용자가 폼에서 직접 고른다.
    CONSTRAINT ck_card_draft_type
        CHECK (card_type IS NULL OR card_type IN ('WALK', 'PLAY', 'HOSPITAL', 'OTHER')),
    -- fallback 은 컬럼이 아니라 fallback_reason IS NOT NULL 로 파생한다.
    CONSTRAINT ck_card_draft_fallback_reason
        CHECK (
            fallback_reason IS NULL
            OR fallback_reason IN ('TIMEOUT', 'MODEL_ERROR', 'INSUFFICIENT_CONTEXT')
        )
);

CREATE INDEX ix_card_draft_room_created
    ON card_drafts (room_id, created_at DESC, id DESC);

CREATE TABLE meeting_cards (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id            BIGINT       NOT NULL REFERENCES chat_rooms(id),
    creator_pet_id     BIGINT       NOT NULL REFERENCES pets(id),
    -- 초안 없이 직접 확정할 수 있어 nullable 이고, 한 초안이 카드를 두 번
    -- 만들지 못하도록 UNIQUE 다.
    source_draft_id    BIGINT       REFERENCES card_drafts(id),
    card_type          VARCHAR(20)  NOT NULL,
    place_text         VARCHAR(500) NOT NULL,
    meet_at            TIMESTAMPTZ  NOT NULL,
    status             VARCHAR(20)  NOT NULL DEFAULT 'OPEN',
    canceled_by_pet_id BIGINT       REFERENCES pets(id),
    canceled_at        TIMESTAMPTZ,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_meeting_card_type
        CHECK (card_type IN ('WALK', 'PLAY', 'HOSPITAL', 'OTHER')),
    CONSTRAINT ck_meeting_card_status
        CHECK (status IN ('OPEN', 'CANCELED')),
    -- 취소 상태와 취소 흔적이 항상 함께 성립해야 한다. 상태만 바꾸고
    -- canceled_by_pet_id 를 비워두는 반쪽 취소를 DB 가 막는다.
    CONSTRAINT ck_meeting_card_cancel CHECK (
        (status = 'CANCELED' AND canceled_by_pet_id IS NOT NULL AND canceled_at IS NOT NULL)
        OR (status = 'OPEN' AND canceled_by_pet_id IS NULL AND canceled_at IS NULL)
    ),
    CONSTRAINT uk_meeting_card_source_draft UNIQUE (source_draft_id)
);

CREATE INDEX ix_meeting_card_room_created
    ON meeting_cards (room_id, created_at DESC, id DESC);

CREATE TABLE meeting_participants (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_card_id  BIGINT       NOT NULL REFERENCES meeting_cards(id),
    pet_id           BIGINT       NOT NULL REFERENCES pets(id),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uk_meeting_participant UNIQUE (meeting_card_id, pet_id)
);

CREATE INDEX ix_meeting_participant_pet
    ON meeting_participants (pet_id, meeting_card_id);

-- chat_messages.meeting_card_id 는 V7 에서 컬럼과 uk_chat_message_card UNIQUE 까지
-- 만들어졌으나 참조 대상 테이블이 없어 FK 를 걸 수 없었다. 이제 연결한다.
-- 컬럼과 기존 제약은 건드리지 않는다. 카드당 CARD 메시지 1건은 이미 그 UNIQUE 가
-- 보장하고 있다.
ALTER TABLE chat_messages
    ADD CONSTRAINT fk_chat_message_meeting_card
        FOREIGN KEY (meeting_card_id) REFERENCES meeting_cards(id);
