CREATE TABLE boards (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(30) NOT NULL,
    version    BIGINT      NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uk_boards_name UNIQUE (name),
    CONSTRAINT ck_boards_name_not_blank CHECK (
        char_length(regexp_replace(name, '\s', '', 'g')) >= 1
    )
);
