CREATE TABLE board_posts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id            BIGINT NOT NULL,
    author_user_id      BIGINT NOT NULL,
    author_pet_id       BIGINT NOT NULL,
    neighborhood_code   VARCHAR(20) NOT NULL,
    title               VARCHAR(120) NOT NULL,
    content             TEXT NOT NULL,
    status              VARCHAR(20) NOT NULL,
    version             BIGINT NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ,

    CONSTRAINT fk_board_posts_board FOREIGN KEY (board_id) REFERENCES boards(id),
    CONSTRAINT fk_board_posts_author_user FOREIGN KEY (author_user_id) REFERENCES users(id),
    CONSTRAINT fk_board_posts_author_pet FOREIGN KEY (author_pet_id) REFERENCES pets(id),
    CONSTRAINT fk_board_posts_neighborhood FOREIGN KEY (neighborhood_code) REFERENCES neighborhoods(code),
    CONSTRAINT ck_board_posts_title_not_blank CHECK (char_length(regexp_replace(title, '\s', '', 'g')) >= 1),
    CONSTRAINT ck_board_posts_content_not_blank CHECK (char_length(regexp_replace(content, '\s', '', 'g')) >= 1),
    CONSTRAINT ck_board_posts_content_length CHECK (char_length(content) <= 5000),
    CONSTRAINT ck_board_posts_status CHECK (status IN ('PUBLISHED', 'DELETED')),
    CONSTRAINT ck_board_posts_status_deleted_at CHECK (
        (status = 'PUBLISHED' AND deleted_at IS NULL)
        OR (status = 'DELETED' AND deleted_at IS NOT NULL)
    )
);

CREATE INDEX ix_board_posts_published_feed
    ON board_posts (board_id, neighborhood_code, created_at DESC, id DESC)
    WHERE status = 'PUBLISHED';

CREATE INDEX ix_board_posts_board_id ON board_posts (board_id);
