ALTER TABLE pets
    DROP CONSTRAINT fk_pets_profile_asset;

ALTER TABLE pets
    ADD CONSTRAINT fk_pets_profile_asset
    FOREIGN KEY (profile_asset_id) REFERENCES media (id);

CREATE TABLE board_post_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    media_id BIGINT NOT NULL,
    display_order INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_board_post_media_post
        FOREIGN KEY (post_id) REFERENCES board_posts (id),
    CONSTRAINT fk_board_post_media_media
        FOREIGN KEY (media_id) REFERENCES media (id),
    CONSTRAINT uk_board_post_media_post_media
        UNIQUE (post_id, media_id),
    CONSTRAINT uk_board_post_media_post_display_order
        UNIQUE (post_id, display_order),
    CONSTRAINT ck_board_post_media_display_order
        CHECK (display_order >= 0 AND display_order < 5)
);
