CREATE TABLE board_post_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    reactor_pet_id BIGINT NOT NULL,
    reaction_type VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_board_post_reactions_post
        FOREIGN KEY (post_id) REFERENCES board_posts (id),
    CONSTRAINT fk_board_post_reactions_reactor_pet
        FOREIGN KEY (reactor_pet_id) REFERENCES pets (id),
    CONSTRAINT uk_board_post_reactions_post_pet_type
        UNIQUE (post_id, reactor_pet_id, reaction_type),
    CONSTRAINT ck_board_post_reactions_type
        CHECK (reaction_type IN ('LIKE'))
);

CREATE INDEX ix_board_post_reactions_reactor_pet_post
    ON board_post_reactions (reactor_pet_id, post_id);
