CREATE TABLE storage_delete_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_key VARCHAR(512) NOT NULL,
    object_version_id VARCHAR(1024),
    reason VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ NOT NULL,
    last_error VARCHAR(500),
    claim_token UUID,
    claimed_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    deleted_once_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_storage_delete_jobs_object_key_reason UNIQUE (object_key, reason),
    CONSTRAINT ck_storage_delete_jobs_reason CHECK (reason IN ('SETLOG_DELETED','UPLOAD_EXPIRED','UPLOAD_REJECTED','UPLOAD_CANCELED','UPLOAD_SURPLUS_VERSIONS')),
    CONSTRAINT ck_storage_delete_jobs_status CHECK (status IN ('PENDING','PROCESSING','RETRY','COMPLETED','FAILED')),
    CONSTRAINT ck_storage_delete_jobs_attempts CHECK (attempts >= 0),
    CONSTRAINT ck_storage_delete_jobs_claim CHECK (
        (status = 'PROCESSING' AND claim_token IS NOT NULL AND claimed_at IS NOT NULL)
        OR (status <> 'PROCESSING' AND claim_token IS NULL AND claimed_at IS NULL)
    ),
    CONSTRAINT ck_storage_delete_jobs_completed CHECK (
        (status = 'COMPLETED' AND completed_at IS NOT NULL)
        OR (status <> 'COMPLETED' AND completed_at IS NULL)
    )
);

CREATE INDEX ix_storage_delete_jobs_claim
    ON storage_delete_jobs (next_retry_at, id)
    WHERE status IN ('PENDING', 'RETRY', 'PROCESSING');

CREATE INDEX ix_setlog_uploads_cleanup_terminal
    ON setlog_uploads (expires_at, id)
    WHERE status IN ('COMPLETED', 'EXPIRED', 'REJECTED', 'CANCELED');
