CREATE TABLE pet_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    registration_number_hmac VARCHAR(64) NOT NULL,
    device_type VARCHAR(20),
    registered_name VARCHAR(100),
    birth_date DATE,
    sex VARCHAR(10),
    breed_name VARCHAR(100),
    neutered BOOLEAN,
    verified_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pet_verifications_pet FOREIGN KEY (pet_id) REFERENCES pets (id),
    CONSTRAINT uk_pet_verifications_pet UNIQUE (pet_id),
    CONSTRAINT uk_pet_verifications_registration_number_hmac UNIQUE (registration_number_hmac),
    CONSTRAINT ck_pet_verifications_registration_number_hmac
        CHECK (registration_number_hmac ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_pet_verifications_device_type
        CHECK (device_type IS NULL OR device_type IN ('IMPLANTED', 'EXTERNAL', 'TAG')),
    CONSTRAINT ck_pet_verifications_provider
        CHECK (provider = 'ANIMAL_INFO_V3'),
    CONSTRAINT ck_pet_verifications_sex
        CHECK (sex IS NULL OR sex IN ('MALE', 'FEMALE'))
);
