CREATE TABLE card_draft_participants (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_draft_id  BIGINT NOT NULL REFERENCES card_drafts(id) ON DELETE CASCADE,
    pet_id         BIGINT NOT NULL REFERENCES pets(id),
    CONSTRAINT uk_card_draft_participant UNIQUE (card_draft_id, pet_id)
);

CREATE INDEX ix_card_draft_participant_pet
    ON card_draft_participants (pet_id, card_draft_id);
