CREATE TABLE admin_actions (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_admin_id  BIGINT        NOT NULL REFERENCES users(id),
    target_type     VARCHAR(30)   NOT NULL,
    target_id       BIGINT        NOT NULL,
    action_type     VARCHAR(50)   NOT NULL,
    reason          VARCHAR(500)  NOT NULL,
    before_state    JSONB,
    after_state     JSONB,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_admin_action_type
        CHECK (action_type IN ('DISMISSED', 'WARNING'))
);

CREATE INDEX ix_admin_actions_target_created
    ON admin_actions (target_type, target_id, created_at DESC, id DESC);

CREATE INDEX ix_reports_status_created_id
    ON reports (status, created_at DESC, id DESC);
