CREATE TABLE notifications (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_pet_id  BIGINT       NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    actor_pet_id   BIGINT       NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    type           VARCHAR(40)  NOT NULL,
    room_id        BIGINT       NOT NULL REFERENCES chat_rooms(id) ON DELETE CASCADE,
    read_at        TIMESTAMPTZ,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_notification_type CHECK (type IN ('OPEN_CHAT_INVITE'))
);

CREATE INDEX idx_notifications_target_created
    ON notifications (target_pet_id, created_at DESC, id DESC);
