CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    nickname VARCHAR(30) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    account_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    neighborhood_code VARCHAR(20) NOT NULL,
    active_pet_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    withdrawn_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_neighborhood
        FOREIGN KEY (neighborhood_code) REFERENCES neighborhoods (code),
    CONSTRAINT ck_users_role
        CHECK (role IN ('USER', 'ADMIN', 'SUPER_ADMIN')),
    CONSTRAINT ck_users_account_status
        CHECK (account_status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN')),
    CONSTRAINT ck_users_withdrawn_at
        CHECK (
            (account_status = 'WITHDRAWN' AND withdrawn_at IS NOT NULL)
            OR account_status <> 'WITHDRAWN'
        )
);

CREATE UNIQUE INDEX uk_users_email_lower ON users (LOWER(email));
CREATE INDEX ix_users_neighborhood_active
    ON users (neighborhood_code, id)
    WHERE account_status = 'ACTIVE';
