CREATE TABLE board_post_comments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id         BIGINT NOT NULL,
    author_user_id  BIGINT NOT NULL,
    author_pet_id   BIGINT NOT NULL,
    content         TEXT NOT NULL,
    version         BIGINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ,

    CONSTRAINT fk_board_post_comments_post
        FOREIGN KEY (post_id) REFERENCES board_posts(id),
    CONSTRAINT fk_board_post_comments_author_user
        FOREIGN KEY (author_user_id) REFERENCES users(id),
    CONSTRAINT fk_board_post_comments_author_pet
        FOREIGN KEY (author_pet_id) REFERENCES pets(id),
    CONSTRAINT ck_board_post_comments_content_not_blank
        CHECK (char_length(regexp_replace(content, '\s', '', 'g')) >= 1),
    CONSTRAINT ck_board_post_comments_content_length
        CHECK (char_length(content) <= 5000)
);

CREATE INDEX ix_board_post_comments_visible_post_created_id
    ON board_post_comments (post_id, created_at ASC, id ASC)
    WHERE deleted_at IS NULL;
