ALTER TABLE board_post_reactions
    DROP CONSTRAINT ck_board_post_reactions_type,
    ADD CONSTRAINT ck_board_post_reactions_type
        CHECK (reaction_type IN ('LIKE', 'HELPFUL'));

CREATE TABLE board_post_comment_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id BIGINT NOT NULL,
    reactor_pet_id BIGINT NOT NULL,
    reaction_type VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_board_post_comment_reactions_comment
        FOREIGN KEY (comment_id) REFERENCES board_post_comments (id),
    CONSTRAINT fk_board_post_comment_reactions_reactor_pet
        FOREIGN KEY (reactor_pet_id) REFERENCES pets (id),
    CONSTRAINT uk_board_post_comment_reactions_comment_pet_type
        UNIQUE (comment_id, reactor_pet_id, reaction_type),
    CONSTRAINT ck_board_post_comment_reactions_type
        CHECK (reaction_type IN ('HELPFUL'))
);

CREATE INDEX ix_board_post_comment_reactions_reactor_pet_comment
    ON board_post_comment_reactions (reactor_pet_id, comment_id);

CREATE INDEX ix_board_posts_visible_author_pet_id
    ON board_posts (author_pet_id, id)
    WHERE deleted_at IS NULL;

CREATE INDEX ix_board_post_comments_visible_author_pet_id
    ON board_post_comments (author_pet_id, id)
    WHERE deleted_at IS NULL;
