CREATE TABLE risk_signal_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    schema_version INTEGER NOT NULL,
    source_type VARCHAR(50) NOT NULL,
    source_id BIGINT NOT NULL,
    signal_type VARCHAR(50) NOT NULL,
    actor_user_id BIGINT NOT NULL,
    target_user_id BIGINT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    payload JSONB NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempts INTEGER NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ NOT NULL,
    last_error VARCHAR(500),
    claim_token UUID,
    claimed_at TIMESTAMPTZ,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_risk_signal_outbox_event_id UNIQUE (event_id),
    CONSTRAINT uk_risk_signal_outbox_source UNIQUE (source_type, source_id, signal_type),
    CONSTRAINT ck_risk_signal_outbox_status CHECK (status IN ('PENDING', 'PROCESSING', 'SENT', 'RETRY', 'FAILED')),
    CONSTRAINT ck_risk_signal_outbox_attempts CHECK (attempts >= 0),
    CONSTRAINT ck_risk_signal_outbox_claim CHECK (
        (status = 'PROCESSING' AND claim_token IS NOT NULL AND claimed_at IS NOT NULL)
        OR (status <> 'PROCESSING' AND claim_token IS NULL AND claimed_at IS NULL)
    ),
    CONSTRAINT ck_risk_signal_outbox_published CHECK (
        (status = 'SENT' AND published_at IS NOT NULL)
        OR (status <> 'SENT' AND published_at IS NULL)
    )
);

CREATE INDEX ix_risk_signal_outbox_claim
    ON risk_signal_outbox (next_retry_at, id)
    WHERE status IN ('PENDING', 'RETRY', 'PROCESSING');
