-- =====================================================================
-- M3 Chat typed message — chat_messages type 확장 + shared_setlog_id + attachments
-- forward-only: 기존 V7 migration은 수정하지 않는다.
-- =====================================================================

-- 1) 사용자 전송 타입(IMAGE/VIDEO/SETLOG_SHARE)을 type CHECK에 추가한다.
ALTER TABLE chat_messages DROP CONSTRAINT ck_chat_message_type;

ALTER TABLE chat_messages ADD CONSTRAINT ck_chat_message_type
    CHECK (type IN ('TEXT', 'CARD', 'IMAGE', 'VIDEO', 'SETLOG_SHARE', 'SYSTEM'));

-- 2) SETLOG_SHARE가 참조하는 setlogId 컬럼. soft delete(setlogs.status)이므로 hard FK는 RESTRICT.
ALTER TABLE chat_messages ADD COLUMN shared_setlog_id BIGINT;

ALTER TABLE chat_messages ADD CONSTRAINT fk_chat_messages_shared_setlog
    FOREIGN KEY (shared_setlog_id) REFERENCES setlogs (id);

-- 3) 타입별 payload CHECK를 새 타입을 포함하도록 forward 교체한다.
ALTER TABLE chat_messages DROP CONSTRAINT ck_chat_message_payload;

ALTER TABLE chat_messages ADD CONSTRAINT ck_chat_message_payload CHECK (
    (type = 'TEXT' AND sender_type = 'PET'
        AND body IS NOT NULL AND BTRIM(body) <> '' AND meeting_card_id IS NULL AND shared_setlog_id IS NULL)
    OR
    (type = 'CARD' AND sender_type = 'PET'
        AND body IS NULL AND meeting_card_id IS NOT NULL AND shared_setlog_id IS NULL)
    OR
    (type = 'SYSTEM' AND sender_type = 'SYSTEM'
        AND body IS NOT NULL AND BTRIM(body) <> '' AND meeting_card_id IS NULL AND shared_setlog_id IS NULL)
    OR
    (type IN ('IMAGE', 'VIDEO') AND sender_type = 'PET'
        AND body IS NULL AND meeting_card_id IS NULL AND shared_setlog_id IS NULL)
    OR
    (type = 'SETLOG_SHARE' AND sender_type = 'PET'
        AND body IS NULL AND meeting_card_id IS NULL AND shared_setlog_id IS NOT NULL)
);

-- 4) IMAGE/VIDEO 첨부 테이블. media_id는 `media`(V12)를 참조한다.
CREATE TABLE chat_message_attachments (
    id               BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id       BIGINT        NOT NULL REFERENCES chat_messages (id) ON DELETE CASCADE,
    media_id         BIGINT        NOT NULL REFERENCES media (id),
    attachment_type  VARCHAR(20)   NOT NULL,
    display_order    SMALLINT      NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_chat_attachment_type
        CHECK (attachment_type IN ('IMAGE', 'VIDEO')),
    CONSTRAINT uk_chat_attachment_message_order
        UNIQUE (message_id, display_order),
    CONSTRAINT uk_chat_attachment_media
        UNIQUE (media_id)
);

-- Message polling: room 단위 조회 뒤 attachment hydrate에 사용.
CREATE INDEX idx_chat_attachment_message_id
    ON chat_message_attachments (message_id);

-- Setlog share hydration: chat_messages.shared_setlog_id lookup.
CREATE INDEX idx_chat_message_shared_setlog
    ON chat_messages (shared_setlog_id);
