CREATE TABLE risk_signal_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    schema_version INTEGER NOT NULL,
    source_type VARCHAR(50) NOT NULL,
    source_id BIGINT NOT NULL,
    signal_type VARCHAR(50) NOT NULL,
    actor_user_id BIGINT NOT NULL,
    target_user_id BIGINT NOT NULL,
    score INTEGER NOT NULL,
    score_policy_version INTEGER NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_risk_signal_events_event_id UNIQUE (event_id),
    CONSTRAINT ck_risk_signal_events_schema CHECK (schema_version = 1),
    CONSTRAINT ck_risk_signal_events_ids CHECK (
        source_id > 0 AND actor_user_id > 0 AND target_user_id > 0
    ),
    CONSTRAINT ck_risk_signal_events_score CHECK (score BETWEEN 0 AND 100),
    CONSTRAINT ck_risk_signal_events_policy CHECK (score_policy_version > 0),
    CONSTRAINT ck_risk_signal_events_contract CHECK (
        (source_type = 'USER_BLOCK' AND signal_type = 'USER_BLOCKED')
        OR (source_type = 'GREETING' AND signal_type = 'GREETING_EXPIRED')
    ),
    CONSTRAINT ck_risk_signal_events_metadata CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX ix_risk_signal_events_source
    ON risk_signal_events (source_type, source_id, signal_type);

CREATE INDEX ix_risk_signal_events_signal_occurred
    ON risk_signal_events (signal_type, occurred_at DESC);

CREATE INDEX ix_risk_signal_events_actor_occurred
    ON risk_signal_events (actor_user_id, occurred_at DESC);

CREATE INDEX ix_risk_signal_events_target_occurred
    ON risk_signal_events (target_user_id, occurred_at DESC);

CREATE INDEX ix_risk_signal_events_actor_target_occurred
    ON risk_signal_events (actor_user_id, target_user_id, occurred_at DESC);
