CREATE TABLE safety_review_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_user_id BIGINT NOT NULL,
    target_user_id BIGINT,
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    total_score BIGINT NOT NULL,
    signal_count BIGINT NOT NULL,
    primary_signal_type VARCHAR(50) NOT NULL,
    evaluation_policy_version INTEGER NOT NULL,
    first_detected_at TIMESTAMPTZ NOT NULL,
    last_detected_at TIMESTAMPTZ NOT NULL,
    last_evaluated_event_id BIGINT NOT NULL,
    evaluated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_safety_review_cases_status CHECK (
        status IN ('OPEN', 'REVIEWING', 'DISMISSED', 'WARNING_RECORDED')
    ),
    CONSTRAINT ck_safety_review_cases_snapshot CHECK (
        subject_user_id > 0
        AND (target_user_id IS NULL OR target_user_id > 0)
        AND total_score >= 0
        AND signal_count > 0
        AND last_evaluated_event_id > 0
        AND evaluation_policy_version > 0
        AND first_detected_at <= last_detected_at
        AND evaluated_at >= last_detected_at
        AND version >= 0
    )
);

CREATE UNIQUE INDEX uk_safety_review_cases_open_subject_target
    ON safety_review_cases (subject_user_id, target_user_id) NULLS NOT DISTINCT
    WHERE status IN ('OPEN', 'REVIEWING');

CREATE INDEX ix_safety_review_cases_queue
    ON safety_review_cases (status, created_at DESC, id DESC);

CREATE INDEX ix_safety_review_cases_subject
    ON safety_review_cases (subject_user_id, last_detected_at DESC, id DESC);

CREATE INDEX ix_safety_review_cases_signal
    ON safety_review_cases (primary_signal_type, last_detected_at DESC, id DESC);

CREATE TABLE safety_case_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL REFERENCES safety_review_cases(id),
    admin_user_id BIGINT NOT NULL,
    action_type VARCHAR(30) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    before_state JSONB NOT NULL,
    after_state JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_safety_case_actions_type CHECK (
        action_type IN ('DISMISSED', 'WARNING_RECORDED')
    ),
    CONSTRAINT ck_safety_case_actions_reason CHECK (length(btrim(reason)) BETWEEN 1 AND 500),
    CONSTRAINT ck_safety_case_actions_states CHECK (
        jsonb_typeof(before_state) = 'object' AND jsonb_typeof(after_state) = 'object'
    )
);

CREATE INDEX ix_safety_case_actions_case_created
    ON safety_case_actions (case_id, created_at DESC, id DESC);

CREATE TABLE evidence_access_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL REFERENCES safety_review_cases(id),
    admin_user_id BIGINT NOT NULL,
    evidence_type VARCHAR(50) NOT NULL,
    resource_id BIGINT,
    purpose VARCHAR(500) NOT NULL,
    access_result VARCHAR(20) NOT NULL,
    failure_code VARCHAR(50),
    accessed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_evidence_access_audits_purpose CHECK (length(btrim(purpose)) BETWEEN 1 AND 500),
    CONSTRAINT ck_evidence_access_audits_result CHECK (
        (access_result = 'SUCCEEDED' AND failure_code IS NULL)
        OR (access_result = 'FAILED' AND failure_code IS NOT NULL)
    ),
    CONSTRAINT ck_evidence_access_audits_resource CHECK (resource_id IS NULL OR resource_id > 0)
);

CREATE INDEX ix_evidence_access_audits_case_accessed
    ON evidence_access_audits (case_id, accessed_at DESC, id DESC);

CREATE INDEX ix_evidence_access_audits_admin_accessed
    ON evidence_access_audits (admin_user_id, accessed_at DESC, id DESC);

CREATE TABLE safety_case_evaluation_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    risk_signal_event_id BIGINT NOT NULL REFERENCES risk_signal_events(id),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempts INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    claimed_at TIMESTAMPTZ,
    worker_id VARCHAR(100),
    claim_token UUID,
    last_error_code VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_safety_case_evaluation_jobs_event UNIQUE (risk_signal_event_id),
    CONSTRAINT ck_safety_case_evaluation_jobs_status CHECK (
        status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')
    ),
    CONSTRAINT ck_safety_case_evaluation_jobs_attempts CHECK (attempts >= 0),
    CONSTRAINT ck_safety_case_evaluation_jobs_claim CHECK (
        (status = 'PROCESSING' AND claimed_at IS NOT NULL AND worker_id IS NOT NULL AND claim_token IS NOT NULL)
        OR (status <> 'PROCESSING' AND claimed_at IS NULL AND worker_id IS NULL AND claim_token IS NULL)
    ),
    CONSTRAINT ck_safety_case_evaluation_jobs_error CHECK (
        last_error_code IS NULL OR length(btrim(last_error_code)) BETWEEN 1 AND 100
    )
);

CREATE INDEX ix_safety_case_evaluation_jobs_due
    ON safety_case_evaluation_jobs (available_at, id)
    WHERE status = 'PENDING';

CREATE INDEX ix_safety_case_evaluation_jobs_stale_claim
    ON safety_case_evaluation_jobs (claimed_at, id)
    WHERE status = 'PROCESSING';

CREATE FUNCTION prevent_safety_audit_mutation() RETURNS trigger
    LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION '% is append-only', TG_TABLE_NAME USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER safety_case_actions_append_only
    BEFORE UPDATE OR DELETE ON safety_case_actions
    FOR EACH ROW EXECUTE FUNCTION prevent_safety_audit_mutation();

CREATE TRIGGER evidence_access_audits_append_only
    BEFORE UPDATE OR DELETE ON evidence_access_audits
    FOR EACH ROW EXECUTE FUNCTION prevent_safety_audit_mutation();
