-- =====================================================================
-- M3 아침 DIRECT 대화 기반 약속 후보 제안 스케줄러 (issue #142)
-- scan: (room_id, source_date) 당 하나. suggestion: AI 후보의 멱등 저장.
-- =====================================================================

-- AI 가 422 로 요청을 거절하면 fallback_reason = 'INVALID_REQUEST' 로 저장된다.
-- 기존 V14 제약을 forward 확장한다. (기존 migration 수정 금지)
ALTER TABLE card_drafts DROP CONSTRAINT ck_card_draft_fallback_reason;

ALTER TABLE card_drafts ADD CONSTRAINT ck_card_draft_fallback_reason
    CHECK (
        fallback_reason IS NULL
        OR fallback_reason IN ('TIMEOUT', 'MODEL_ERROR', 'INSUFFICIENT_CONTEXT', 'INVALID_REQUEST')
    );

-- 동일 방 + 소스 날짜에 Scan 은 하나다(uk_meeting_suggestion_scan).
-- claim/lease 필드는 RiskSignal Outbox(V34/V36) 패턴을 따른다.
CREATE TABLE meeting_suggestion_scans (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id         BIGINT       NOT NULL REFERENCES chat_rooms(id) ON DELETE CASCADE,
    source_date     DATE         NOT NULL,
    reference_date  DATE         NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    attempts        INTEGER      NOT NULL DEFAULT 0,
    next_retry_at   TIMESTAMPTZ  NOT NULL,
    claim_token     UUID,
    claimed_at      TIMESTAMPTZ,
    last_error      VARCHAR(500),
    completed_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_meeting_suggestion_scan
        UNIQUE (room_id, source_date),
    CONSTRAINT ck_meeting_suggestion_scan_status CHECK (
        status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED_RETRYABLE', 'FAILED_FINAL')
    ),
    CONSTRAINT ck_meeting_suggestion_scan_attempts CHECK (attempts >= 0),
    -- PROCESSING 일 때만 claim 흔적이 있고, 그 외 상태에는 없어야 한다.
    CONSTRAINT ck_meeting_suggestion_scan_claim CHECK (
        (status = 'PROCESSING' AND claim_token IS NOT NULL AND claimed_at IS NOT NULL)
        OR (status <> 'PROCESSING' AND claim_token IS NULL AND claimed_at IS NULL)
    ),
    -- 종료 상태와 종료 시각이 항상 함께 성립한다.
    CONSTRAINT ck_meeting_suggestion_scan_terminal CHECK (
        (status IN ('COMPLETED', 'FAILED_FINAL') AND completed_at IS NOT NULL)
        OR (status NOT IN ('COMPLETED', 'FAILED_FINAL') AND completed_at IS NULL)
    )
);

-- claim 후보 조회: 만기(PENDING/FAILED_RETRYABLE)와 stale lease(PROCESSING)를
-- 나눠 인덱싱한다(Risk V36 과 동일한 형태).
CREATE INDEX ix_meeting_suggestion_scan_due
    ON meeting_suggestion_scans (next_retry_at, id)
    WHERE status IN ('PENDING', 'FAILED_RETRYABLE');

CREATE INDEX ix_meeting_suggestion_scan_stale
    ON meeting_suggestion_scans (claimed_at, id)
    WHERE status = 'PROCESSING';

-- Scan 1 : N Suggestion. AI 후보에는 안정 ID가 없으므로 canonical 의미를
-- 정규화한 fingerprint 로 멱등성을 잡는다. DB UNIQUE 가 최종 방어선이다.
CREATE TABLE meeting_suggestions (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id      BIGINT       NOT NULL REFERENCES meeting_suggestion_scans(id) ON DELETE CASCADE,
    fingerprint  VARCHAR(64)  NOT NULL,
    card_type    VARCHAR(20),
    meet_date    VARCHAR(100),
    meet_time    VARCHAR(100),
    place_text   VARCHAR(500),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_meeting_suggestion_fingerprint UNIQUE (fingerprint),
    CONSTRAINT ck_meeting_suggestion_type CHECK (
        card_type IS NULL OR card_type IN ('WALK', 'PLAY', 'HOSPITAL', 'OTHER')
    )
);

CREATE INDEX ix_meeting_suggestion_scan
    ON meeting_suggestions (scan_id, id);

-- Scheduler 의 TEXT 조회 인덱스. DirectRoomConversationQueryService 의 두 조회가
-- (room_id, type='TEXT', sender_type='PET', created_at 기간) 조건을 쓰고, 최신 30건은
-- created_at DESC, id DESC 로 정렬한다. 기존 idx_chat_message_room_id(room_id, id) 는
-- 타입·발신자 필터와 created_at 정렬을 커버하지 못해 이력이 긴 방에서 매번 스캔+정렬이
-- 발생하므로, 조회 조건과 동일한 형태의 partial index 를 둔다. 기존 인덱스는 유지한다.
CREATE INDEX idx_chat_message_scheduler_text
    ON chat_messages (room_id, created_at DESC, id DESC)
    WHERE type = 'TEXT' AND sender_type = 'PET';
