ALTER TABLE users
    ALTER COLUMN password_hash DROP NOT NULL;

CREATE TABLE oauth_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(20) NOT NULL,
    provider_subject VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_oauth_identities_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_oauth_identities_provider_subject
        UNIQUE (provider, provider_subject),
    CONSTRAINT uk_oauth_identities_user_provider
        UNIQUE (user_id, provider),
    CONSTRAINT ck_oauth_identities_provider
        CHECK (provider IN ('GOOGLE', 'NAVER'))
);

CREATE TABLE oauth_login_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL,
    provider VARCHAR(20) NOT NULL,
    provider_subject VARCHAR(255) NOT NULL,
    verified_email VARCHAR(320),
    status VARCHAR(20) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    consumed_at TIMESTAMPTZ,
    CONSTRAINT uk_oauth_login_codes_token_hash UNIQUE (token_hash),
    CONSTRAINT ck_oauth_login_codes_hash
        CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_oauth_login_codes_provider
        CHECK (provider IN ('GOOGLE', 'NAVER')),
    CONSTRAINT ck_oauth_login_codes_status
        CHECK (status IN ('AVAILABLE', 'CONSUMED')),
    CONSTRAINT ck_oauth_login_codes_available_email
        CHECK (status <> 'AVAILABLE' OR verified_email IS NOT NULL),
    CONSTRAINT ck_oauth_login_codes_expiry
        CHECK (expires_at > created_at)
);

CREATE INDEX ix_oauth_login_codes_expires_at
    ON oauth_login_codes (expires_at);

CREATE TABLE oauth_signup_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL,
    provider VARCHAR(20) NOT NULL,
    provider_subject VARCHAR(255) NOT NULL,
    verified_email VARCHAR(320),
    status VARCHAR(20) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    consumed_at TIMESTAMPTZ,
    CONSTRAINT uk_oauth_signup_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT ck_oauth_signup_tokens_hash
        CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_oauth_signup_tokens_provider
        CHECK (provider IN ('GOOGLE', 'NAVER')),
    CONSTRAINT ck_oauth_signup_tokens_status
        CHECK (status IN ('AVAILABLE', 'CONSUMED')),
    CONSTRAINT ck_oauth_signup_tokens_available_email
        CHECK (status <> 'AVAILABLE' OR verified_email IS NOT NULL),
    CONSTRAINT ck_oauth_signup_tokens_expiry
        CHECK (expires_at > created_at)
);

CREATE INDEX ix_oauth_signup_tokens_expires_at
    ON oauth_signup_tokens (expires_at);
