-- 만남 위치 제출·양쪽 확인(#111) 기반 테이블. 01_M3_통합_ERD.md §6 Meeting 참조.
-- meeting_cards 의 OPEN -> CANCELED lifecycle 은 건드리지 않고, 별도 모델로 만남 검증을 관리한다.
-- Location 평가(좌표·freshness·accuracy)와 약속 시간창·거리·양쪽 제출 간격 판정은
-- MeetingVerificationService 가 수행하고, 실제 GPS 확정이 meetings 에 최종 정본으로 남는다.
--
-- meetings 는 GPS 또는 Code 방식으로 실제 만남이 확정된 최종 정본이다. 확정 시점에만
-- 생성되며 미확정 상태(NOT_SUBMITTED/WAITING_COUNTERPART/CODE_REQUIRED/...)를 저장하지 않는다.
-- 제출·대기 상태는 meeting_verifications 행의 존재와 양쪽 제출 여부로 표현한다.
-- GPS 확정은 실제 계산 거리(distance_meters)를 저장하고, Code 확정은 거리값이 없어 null 이다.

CREATE TABLE meetings (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_card_id     BIGINT       NOT NULL REFERENCES meeting_cards(id),
    -- 확정 방식. Meeting 은 확정 시점에만 생성되므로 값이 항상 존재한다.
    verification_method VARCHAR(20)  NOT NULL,
    confirmed_at        TIMESTAMPTZ  NOT NULL,
    -- GPS 확정 시 계산한 실제 두 위치 사이 거리(미터). Code 확정은 거리값이 없다.
    distance_meters     DOUBLE PRECISION,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- 같은 약속 카드로 만남이 두 번 만들어지지 않는다. Pair lock + MeetingCard 행 잠금이
    -- 정상 경쟁 제어의 정본이고 이 UNIQUE 는 최후 방어다.
    CONSTRAINT uk_meeting_card UNIQUE (meeting_card_id),
    CONSTRAINT ck_meeting_verification_method CHECK (
        verification_method IN ('GPS', 'CODE')
    ),
    CONSTRAINT ck_meeting_distance_non_negative CHECK (
        distance_meters IS NULL OR distance_meters >= 0
    ),
    -- GPS 는 실제 거리 필수, CODE 는 거리 없음(null)을 DB 가 강제한다.
    CONSTRAINT ck_meeting_distance_by_method CHECK (
        (verification_method = 'GPS' AND distance_meters IS NOT NULL)
        OR (verification_method = 'CODE' AND distance_meters IS NULL)
    )
);

CREATE TABLE meeting_verifications (
    id                 BIGINT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_card_id    BIGINT            NOT NULL,
    -- 제출자 Pet snapshot. M1 DIRECT 카드는 정확히 두 행이 생긴다.
    participant_pet_id BIGINT            NOT NULL,
    -- Location 판정 결과. ACCEPTABLE 은 SUBMITTED, LOW_ACCURACY 는 CODE_REQUIRED 로 저장한다.
    status             VARCHAR(30)       NOT NULL DEFAULT 'SUBMITTED',
    -- raw 위치 보관 컬럼. SUBMITTED 에서만 필수이고, CODE_REQUIRED/ACCEPTED/REJECTED/EXPIRED
    -- 전환 시 scrub(null)한다. 무기한 보관을 강제하는 NOT NULL 을 두지 않는다.
    latitude           DOUBLE PRECISION,
    longitude          DOUBLE PRECISION,
    accuracy_meters    DOUBLE PRECISION,
    captured_at        TIMESTAMPTZ,
    -- 서버 수신시각. 양쪽 제출 간격 정책의 정본이다. captured_at 은 측위시각으로만 쓴다.
    submitted_at       TIMESTAMPTZ       NOT NULL,
    -- 현재 Pet 의 최신 제출이 사용한 멱등키. 영구 멱등 정본은
    -- meeting_verification_requests(client_request_id PK)이고 이 컬럼은 최신값 추적용이다.
    client_request_id  UUID              NOT NULL,
    created_at         TIMESTAMPTZ       NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ       NOT NULL DEFAULT now(),

    -- Pet 당 제출 1건. 같은 Pet 이 새 clientRequestId 로 다시 제출하면 행을 대체한다.
    CONSTRAINT uk_meeting_verification_pet UNIQUE (meeting_card_id, participant_pet_id),
    CONSTRAINT ck_meeting_verification_status CHECK (
        status IN ('SUBMITTED', 'CODE_REQUIRED', 'ACCEPTED', 'REJECTED', 'EXPIRED')
    ),
    -- raw 위치는 GPS 판정이 필요한 SUBMITTED 에서만 보관하고 나머지 상태에서는 null 이다.
    CONSTRAINT ck_meeting_verification_raw CHECK (
        (status = 'SUBMITTED'
            AND latitude IS NOT NULL
            AND longitude IS NOT NULL
            AND accuracy_meters IS NOT NULL
            AND captured_at IS NOT NULL)
        OR (status IN ('CODE_REQUIRED', 'ACCEPTED', 'REJECTED', 'EXPIRED')
            AND latitude IS NULL
            AND longitude IS NULL
            AND accuracy_meters IS NULL
            AND captured_at IS NULL)
    ),
    -- verification 은 실제 카드 참여 Pet 만 남길 수 있다. V14 의
    -- uk_meeting_participant (meeting_card_id, pet_id) UNIQUE 를 참조한다.
    CONSTRAINT fk_meeting_verification_participant
        FOREIGN KEY (meeting_card_id, participant_pet_id)
        REFERENCES meeting_participants (meeting_card_id, pet_id)
);

-- uk_meeting_verification_pet 가 (meeting_card_id, participant_pet_id) B-tree 를 이미
-- 만들므로 동일 컬럼의 별도 index 는 두지 않는다.

-- 영구 request 멱등 원장(immutable). 같은 Pet 이 새 clientRequestId 로 제출해도
-- 과거 request ID 가 사라지지 않아 늦은 재시도(AAA → BBB → 늦은 AAA)도 replay 로 수렴한다.
-- clientRequestId 는 전역에서 유일해야 하므로 synthetic ID 없이 그 자체가 PK 이다.
-- raw 좌표는 보관하지 않고 HMAC-SHA-256 fingerprint 만 남긴다.
CREATE TABLE meeting_verification_requests (
    client_request_id  UUID              NOT NULL,
    meeting_card_id    BIGINT            NOT NULL,
    participant_pet_id BIGINT            NOT NULL,
    -- Location 판정 결과. 제출 단계에서는 SUBMITTED 또는 CODE_REQUIRED 만 남는다.
    status             VARCHAR(30)       NOT NULL,
    -- canonical payload 의 서버 비밀키 HMAC-SHA-256 hex. raw 좌표를 되돌릴 수 없다.
    fingerprint        VARCHAR(64)       NOT NULL,
    created_at         TIMESTAMPTZ       NOT NULL DEFAULT now(),

    CONSTRAINT pk_meeting_verification_requests PRIMARY KEY (client_request_id),
    CONSTRAINT ck_meeting_verification_request_status CHECK (
        status IN ('SUBMITTED', 'CODE_REQUIRED')
    ),
    -- 원장도 실제 카드 참여 Pet 만 남길 수 있다. V14 의 uk_meeting_participant
    -- (meeting_card_id, pet_id) UNIQUE 를 참조한다. 독립 meeting_cards/pets FK 는
    -- 이 composite FK 와 meeting_participants 의 FK 로 전이적으로 보장되므로 두지 않는다.
    CONSTRAINT fk_meeting_verification_request_participant
        FOREIGN KEY (meeting_card_id, participant_pet_id)
        REFERENCES meeting_participants (meeting_card_id, pet_id)
);
