-- 만남 위치 제출·양쪽 확인(#111) 기반 테이블. 01_M3_통합_ERD.md §6 Meeting 참조.
-- meeting_cards 의 OPEN -> CANCELED lifecycle 은 건드리지 않고, 별도 모델로 만남 검증을 관리한다.
-- #146 Location 계약 미병합: 좌표·accuracy·거리 판정과 Confirmation Code 는 이후 태스크에서 구현한다.
--
-- meetings 는 GPS 또는 Code 방식으로 실제 만남이 확정된 최종 정본이다. 확정 시점에만
-- 생성되며 미확정 상태(NOT_SUBMITTED/WAITING_COUNTERPART/CODE_REQUIRED/...)를 저장하지 않는다.
-- 제출·대기 상태는 meeting_verifications 행의 존재와 양쪽 제출 여부로 표현한다.

CREATE TABLE meetings (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_card_id     BIGINT       NOT NULL REFERENCES meeting_cards(id),
    -- 확정 방식. Meeting 은 확정 시점에만 생성되므로 값이 항상 존재한다.
    verification_method VARCHAR(20)  NOT NULL,
    confirmed_at        TIMESTAMPTZ  NOT NULL,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- 같은 약속 카드로 만남이 두 번 만들어지지 않는다.
    CONSTRAINT uk_meeting_card UNIQUE (meeting_card_id),
    CONSTRAINT ck_meeting_verification_method CHECK (
        verification_method IN ('GPS', 'CODE')
    )
);

CREATE TABLE meeting_verifications (
    id                 BIGINT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_card_id    BIGINT            NOT NULL REFERENCES meeting_cards(id),
    -- 제출자 Pet snapshot. M1 DIRECT 카드는 정확히 두 행이 생긴다.
    participant_pet_id BIGINT            NOT NULL REFERENCES pets(id),
    -- 01_M3_통합_ERD.md: SUBMITTED/CODE_REQUIRED/ACCEPTED/REJECTED.
    -- 지금은 SUBMITTED 만 기록하고, 나머지는 #146 병합 뒤 판정에서 설정한다.
    status             VARCHAR(30)       NOT NULL DEFAULT 'SUBMITTED',
    latitude           DOUBLE PRECISION  NOT NULL,
    longitude          DOUBLE PRECISION  NOT NULL,
    accuracy_meters    DOUBLE PRECISION  NOT NULL,
    captured_at        TIMESTAMPTZ       NOT NULL,
    -- 동일 Pet 재요청 식별용 전역 멱등키.
    client_request_id  UUID              NOT NULL,
    created_at         TIMESTAMPTZ       NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ       NOT NULL DEFAULT now(),

    -- Pet 당 제출 1건. 같은 Pet 이 새 clientRequestId 로 다시 제출하면 행을 대체한다.
    CONSTRAINT uk_meeting_verification_pet UNIQUE (meeting_card_id, participant_pet_id),
    CONSTRAINT uk_meeting_verification_client_request UNIQUE (client_request_id),
    CONSTRAINT ck_meeting_verification_status CHECK (
        status IN ('SUBMITTED', 'CODE_REQUIRED', 'ACCEPTED', 'REJECTED')
    )
);

CREATE INDEX ix_meeting_verification_card_pet
    ON meeting_verifications (meeting_card_id, participant_pet_id);
