CREATE TABLE medical_support_programs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_organization VARCHAR(200) NOT NULL,
    stable_source_program_id VARCHAR(200),
    region_code VARCHAR(30) NOT NULL,
    region_sido_name VARCHAR(50) NOT NULL,
    region_sigungu_name VARCHAR(50),
    normalized_program_name VARCHAR(300) NOT NULL,
    program_year INTEGER NOT NULL,
    program_name VARCHAR(500) NOT NULL,
    summary VARCHAR(2000), support_amount VARCHAR(1000), application_period VARCHAR(1000),
    support_target TEXT, support_items TEXT, application_method TEXT,
    animal_registration_condition TEXT, income_welfare_condition TEXT, contact TEXT,
    hospital_policy VARCHAR(40) NOT NULL, program_status VARCHAR(40) NOT NULL,
    official_source_url VARCHAR(2000) NOT NULL, last_verified_at TIMESTAMPTZ NOT NULL,
    current_verified_revision_id BIGINT, version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_medical_support_program_year CHECK (program_year BETWEEN 2000 AND 2100),
    CONSTRAINT ck_medical_support_program_policy CHECK (hospital_policy IN ('DESIGNATED_LIST','REGIONAL_ELIGIBLE_PROVIDER','NOT_PUBLISHED')),
    CONSTRAINT ck_medical_support_program_status CHECK (program_status IN ('SCHEDULED','OPEN','CLOSED','BUDGET_EXHAUSTED','UNKNOWN'))
);
CREATE UNIQUE INDEX ux_medical_support_program_stable_identity ON medical_support_programs (source_organization, stable_source_program_id) WHERE stable_source_program_id IS NOT NULL;
CREATE UNIQUE INDEX ux_medical_support_program_fallback_identity ON medical_support_programs (source_organization, region_code, normalized_program_name, program_year) WHERE stable_source_program_id IS NULL;
CREATE INDEX ix_medical_support_program_region ON medical_support_programs (region_sido_name, region_sigungu_name, id);

CREATE TABLE medical_support_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT REFERENCES medical_support_programs(id),
    source_url VARCHAR(2000) NOT NULL, source_document_url VARCHAR(2000), source_organization VARCHAR(200) NOT NULL,
    source_published_at TIMESTAMPTZ, fetched_at TIMESTAMPTZ NOT NULL, source_hash VARCHAR(64) NOT NULL,
    content_type VARCHAR(200), parser_version VARCHAR(100) NOT NULL,
    stable_source_program_id VARCHAR(200), region_code VARCHAR(30), region_sido_name VARCHAR(50), region_sigungu_name VARCHAR(50),
    program_year INTEGER, program_name VARCHAR(500), normalized_program_name VARCHAR(300),
    summary VARCHAR(2000), support_amount VARCHAR(1000), application_period VARCHAR(1000),
    support_target TEXT, support_items TEXT, application_method TEXT, animal_registration_condition TEXT,
    income_welfare_condition TEXT, contact TEXT, hospital_policy VARCHAR(40), program_status VARCHAR(40), semantic_fingerprint VARCHAR(64),
    review_status VARCHAR(30) NOT NULL, change_type VARCHAR(30), reviewer_id BIGINT, reviewed_at TIMESTAMPTZ, rejection_reason VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_medical_support_revision_source_hash UNIQUE (source_url, source_hash),
    CONSTRAINT ck_medical_support_revision_review CHECK (review_status IN ('PENDING_REVIEW','VERIFIED','REJECTED')),
    CONSTRAINT ck_medical_support_revision_change CHECK (change_type IS NULL OR change_type IN ('NEW','UPDATED','UNCHANGED'))
);
CREATE INDEX ix_medical_support_revision_program_verified ON medical_support_revisions (program_id, review_status, id DESC);
ALTER TABLE medical_support_programs ADD CONSTRAINT fk_medical_support_program_current_revision FOREIGN KEY (current_verified_revision_id) REFERENCES medical_support_revisions(id);

CREATE TABLE medical_support_revision_hospitals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id BIGINT NOT NULL REFERENCES medical_support_revisions(id) ON DELETE CASCADE,
    name VARCHAR(300) NOT NULL, address VARCHAR(1000), phone VARCHAR(100), sido_name VARCHAR(50), sigungu_name VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX ix_medical_support_revision_hospital_revision ON medical_support_revision_hospitals (revision_id, id);

CREATE TABLE medical_support_ingestion_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key VARCHAR(40) NOT NULL, source_url VARCHAR(2000) NOT NULL,
    attempted_at TIMESTAMPTZ NOT NULL, outcome VARCHAR(20) NOT NULL, failure_reason VARCHAR(1000),
    content_type VARCHAR(200), source_hash VARCHAR(64), revision_id BIGINT REFERENCES medical_support_revisions(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_medical_support_ingestion_attempt_outcome CHECK (outcome IN ('SUCCEEDED','FAILED')),
    CONSTRAINT ck_medical_support_ingestion_attempt_result CHECK ((outcome = 'SUCCEEDED' AND failure_reason IS NULL) OR (outcome = 'FAILED' AND failure_reason IS NOT NULL))
);
CREATE INDEX ix_medical_support_ingestion_attempt_source_time ON medical_support_ingestion_attempts (source_key, attempted_at DESC, id DESC);
