CREATE TABLE media_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    purpose VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    object_key VARCHAR(512) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_media_assets_owner
        FOREIGN KEY (owner_user_id) REFERENCES users (id),
    CONSTRAINT uk_media_assets_object_key UNIQUE (object_key),
    CONSTRAINT ck_media_assets_purpose
        CHECK (purpose IN ('SETLOG', 'PROFILE', 'FOURCUT_SOURCE', 'FOURCUT_RESULT')),
    CONSTRAINT ck_media_assets_status
        CHECK (status IN ('PENDING', 'UPLOADED', 'EXPIRED', 'DELETE_REQUESTED', 'DELETED')),
    CONSTRAINT ck_media_assets_size CHECK (size_bytes > 0)
);

CREATE INDEX ix_media_assets_owner_created
    ON media_assets (owner_user_id, created_at DESC);

CREATE INDEX ix_media_assets_pending_expiry
    ON media_assets (expires_at, id)
    WHERE status = 'PENDING';

CREATE INDEX ix_media_assets_delete_requested
    ON media_assets (id)
    WHERE status = 'DELETE_REQUESTED';
