-- LOW_ACCURACY fallback의 현재 활성 코드. 평문 4자리 코드는 어떤 컬럼에도 저장하지 않는다.
CREATE TABLE meeting_confirmation_codes (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_card_id       BIGINT       NOT NULL,
    issuer_pet_id         BIGINT       NOT NULL,
    code_hash             VARCHAR(255) NOT NULL,
    expires_at            TIMESTAMPTZ  NOT NULL,
    failed_attempts       INTEGER      NOT NULL DEFAULT 0,
    verifier_pet_id       BIGINT,
    verifier_confirmed_at TIMESTAMPTZ,
    issuer_confirmed_at   TIMESTAMPTZ,
    invalidated_at        TIMESTAMPTZ,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uk_meeting_confirmation_code_card UNIQUE (meeting_card_id),
    CONSTRAINT ck_meeting_confirmation_code_attempts CHECK (failed_attempts >= 0),
    CONSTRAINT ck_meeting_confirmation_code_verifier CHECK (
        (verifier_pet_id IS NULL AND verifier_confirmed_at IS NULL)
        OR (verifier_pet_id IS NOT NULL AND verifier_confirmed_at IS NOT NULL)
    ),
    -- 발급자와 검증자는 서로 다른 Pet 이어야 한다(검증자는 null 허용).
    CONSTRAINT ck_meeting_confirmation_code_distinct_issuer_verifier CHECK (
        verifier_pet_id IS NULL OR verifier_pet_id <> issuer_pet_id
    ),
    -- 생성자(issuer) 확인은 상대(verifier) 검증 뒤에만 가능하다.
    CONSTRAINT ck_meeting_confirmation_code_issuer_confirm_after_verifier CHECK (
        issuer_confirmed_at IS NULL OR verifier_confirmed_at IS NOT NULL
    ),
    -- 카드 참여 Pet 만 발급·검증할 수 있다. V14 의 uk_meeting_participant
    -- (meeting_card_id, pet_id) UNIQUE 를 참조한다. 독립 meeting_cards/pets FK 는
    -- 이 composite FK 와 meeting_participants 의 FK 로 전이적으로 보장되므로 두지 않는다.
    CONSTRAINT fk_meeting_confirmation_code_issuer_participant
        FOREIGN KEY (meeting_card_id, issuer_pet_id)
        REFERENCES meeting_participants (meeting_card_id, pet_id),
    CONSTRAINT fk_meeting_confirmation_code_verifier_participant
        FOREIGN KEY (meeting_card_id, verifier_pet_id)
        REFERENCES meeting_participants (meeting_card_id, pet_id)
);
