-- 만남 후기·발자국(#150). 01_M3_통합_ERD.md §6 meeting_reviews/footprints 참조.
-- 실제 확정된 Meeting(meetings 행)이 있는 경우에만 후기를 쓸 수 있고,
-- 후기 저장과 "신규 발자국 생성 여부 판단·생성"은 하나의 트랜잭션으로 처리한다.
--
-- 발자국의 하루 기준은 Asia/Seoul 이며 earned_date 에 후기 제출 시각을 KST 로
-- 변환한 날짜를 저장한다. 같은 Pet 의 같은 KST 날짜 발자국은 최대 한 건이다.
-- 같은 날 다른 Meeting 의 후기는 저장할 수 있고, 이미 그날 발자국이 있으면
-- 새 발자국은 만들지 않는다(uk_footprint_pet_date 가 최종 방어선).

CREATE TABLE meeting_reviews (
    id                BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id        BIGINT      NOT NULL REFERENCES meetings(id),
    reviewer_pet_id   BIGINT      NOT NULL REFERENCES pets(id),
    -- 필수 장소 태그(공백 불가, 최대 30자). 허용 태그 enum/공용 DTO 가 없어 String 으로 저장한다.
    place_tag         VARCHAR(30) NOT NULL,
    -- 동일 Pet 재요청 식별용 전역 멱등키(meeting_verifications 와 같은 패턴).
    client_request_id UUID        NOT NULL,
    -- 한 줄 후기. 선택 입력(null 허용).
    content           VARCHAR(500),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- 같은 (meeting, reviewer_pet) 후기는 한 번만. 동시 중복 후기의 최종 방어선.
    CONSTRAINT uk_meeting_review_pet UNIQUE (meeting_id, reviewer_pet_id),
    CONSTRAINT uk_meeting_review_client_request UNIQUE (client_request_id)
);

CREATE TABLE footprints (
    id                 BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id         BIGINT      NOT NULL REFERENCES meetings(id),
    -- 후기 제출자(=발자국 수신자) Pet snapshot.
    receiver_pet_id    BIGINT      NOT NULL REFERENCES pets(id),
    -- 상대 Pet snapshot. M1 DIRECT 카드는 정확히 한 명.
    counterpart_pet_id BIGINT      NOT NULL REFERENCES pets(id),
    -- Asia/Seoul 기준 날짜.
    earned_date        DATE        NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- 같은 만남·같은 Pet 발자국은 한 번만(후기 1건당 발자국 1건).
    CONSTRAINT uk_footprint_meeting_pet UNIQUE (meeting_id, receiver_pet_id),
    -- 같은 Pet 은 같은 KST 날짜에 발자국 1건. 일일 중복의 최종 방어선.
    CONSTRAINT uk_footprint_pet_date UNIQUE (receiver_pet_id, earned_date)
);

CREATE INDEX ix_footprints_receiver_created
    ON footprints (receiver_pet_id, created_at DESC, id DESC);
