-- =====================================================================
-- M1-014 DIRECT Chat Core — chat_rooms, chat_room_participants, chat_messages
-- FK to pets, meeting_cards 생략 (추후 ALTER로 추가)
-- =====================================================================

CREATE TABLE chat_rooms (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type             VARCHAR(20)  NOT NULL DEFAULT 'DIRECT',
    status           VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    origin           VARCHAR(20)  NOT NULL,
    pet_low_id       BIGINT,
    pet_high_id      BIGINT,
    last_message_at  TIMESTAMPTZ,
    archived_at      TIMESTAMPTZ,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_chat_room_type
        CHECK (type IN ('DIRECT', 'GROUP')),
    CONSTRAINT ck_chat_room_status
        CHECK (status IN ('ACTIVE', 'ARCHIVED')),
    CONSTRAINT ck_chat_room_origin
        CHECK (origin IN ('GREETING', 'FRIEND')),
    CONSTRAINT ck_chat_room_direct_pair
        CHECK (
            (type = 'DIRECT'
                AND pet_low_id IS NOT NULL
                AND pet_high_id IS NOT NULL
                AND pet_low_id < pet_high_id)
            OR
            (type = 'GROUP'
                AND pet_low_id IS NULL
                AND pet_high_id IS NULL)
        )
);

CREATE UNIQUE INDEX uk_chat_room_direct_pair
    ON chat_rooms (pet_low_id, pet_high_id)
    WHERE type = 'DIRECT';

CREATE TABLE chat_room_participants (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id    BIGINT       NOT NULL REFERENCES chat_rooms(id) ON DELETE CASCADE,
    pet_id     BIGINT       NOT NULL,
    joined_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at    TIMESTAMPTZ,

    CONSTRAINT uk_chat_participant UNIQUE (room_id, pet_id)
);

CREATE TABLE chat_messages (
    id                 BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id            BIGINT        NOT NULL REFERENCES chat_rooms(id) ON DELETE CASCADE,
    sender_type        VARCHAR(20)   NOT NULL,
    sender_pet_id      BIGINT,
    type               VARCHAR(20)   NOT NULL,
    body               VARCHAR(2000),
    meeting_card_id    BIGINT,
    client_message_id  VARCHAR(64),
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_chat_message_sender CHECK (
        (sender_type = 'PET' AND sender_pet_id IS NOT NULL)
        OR (sender_type = 'SYSTEM' AND sender_pet_id IS NULL)
    ),
    CONSTRAINT ck_chat_message_type
        CHECK (type IN ('TEXT', 'CARD', 'SYSTEM')),
    CONSTRAINT ck_chat_message_payload CHECK (
        (type = 'TEXT' AND sender_type = 'PET'
            AND body IS NOT NULL AND BTRIM(body) <> '' AND meeting_card_id IS NULL)
        OR
        (type = 'CARD' AND sender_type = 'PET'
            AND body IS NULL AND meeting_card_id IS NOT NULL)
        OR
        (type = 'SYSTEM' AND sender_type = 'SYSTEM'
            AND body IS NOT NULL AND BTRIM(body) <> '' AND meeting_card_id IS NULL)
    ),
    CONSTRAINT uk_chat_message_client
        UNIQUE (room_id, client_message_id),
    CONSTRAINT uk_chat_message_card
        UNIQUE (meeting_card_id)
);
