CREATE TABLE pets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    public_tag VARCHAR(30) NOT NULL,
    nickname VARCHAR(30) NOT NULL,
    breed_code VARCHAR(30),
    breed_name VARCHAR(100),
    sex VARCHAR(10),
    neutered BOOLEAN,
    birth_date DATE,
    weight_kg NUMERIC(5,2),
    size_code VARCHAR(20),
    bio VARCHAR(500),
    personality_tags JSONB,
    care_note VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    profile_asset_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_pets_owner
        FOREIGN KEY (owner_user_id) REFERENCES users (id),
    CONSTRAINT fk_pets_profile_asset
        FOREIGN KEY (profile_asset_id) REFERENCES media_assets (id),
    CONSTRAINT uk_pets_public_tag UNIQUE (public_tag),
    CONSTRAINT ck_pets_public_tag_format
        CHECK (public_tag ~ '^.{1,25}#[A-Z0-9]{4}$'),
    CONSTRAINT ck_pets_nickname
        CHECK (char_length(nickname) >= 1),
    CONSTRAINT ck_pets_sex
        CHECK (sex IS NULL OR sex IN ('MALE', 'FEMALE', 'UNKNOWN')),
    CONSTRAINT ck_pets_size_code
        CHECK (size_code IS NULL OR size_code IN ('SMALL', 'MEDIUM', 'LARGE')),
    CONSTRAINT ck_pets_weight_kg
        CHECK (
            weight_kg IS NULL
            OR (weight_kg >= 0 AND weight_kg <= 999.99)
        ),
    CONSTRAINT ck_pets_status
        CHECK (status IN ('ACTIVE', 'SUSPENDED', 'DELETED')),
    CONSTRAINT ck_pets_status_deleted_at
        CHECK (
            (status = 'DELETED' AND deleted_at IS NOT NULL)
            OR
            (status IN ('ACTIVE', 'SUSPENDED') AND deleted_at IS NULL)
        )
);

CREATE INDEX ix_pets_owner_not_deleted_created
    ON pets (owner_user_id, created_at, id)
    WHERE deleted_at IS NULL;

ALTER TABLE users
    ADD CONSTRAINT fk_users_active_pet
    FOREIGN KEY (active_pet_id) REFERENCES pets (id);
