CREATE TABLE friend_requests (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_pet_id  BIGINT       NOT NULL,
    target_pet_id     BIGINT       NOT NULL,
    pair_low_id       BIGINT       GENERATED ALWAYS AS
        (LEAST(requester_pet_id, target_pet_id)) STORED,
    pair_high_id      BIGINT       GENERATED ALWAYS AS
        (GREATEST(requester_pet_id, target_pet_id)) STORED,
    status            VARCHAR(20)  NOT NULL,
    requested_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    responded_at      TIMESTAMPTZ,
    expires_at        TIMESTAMPTZ  NOT NULL,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_friend_requests_requester_pet
        FOREIGN KEY (requester_pet_id) REFERENCES pets (id),
    CONSTRAINT fk_friend_requests_target_pet
        FOREIGN KEY (target_pet_id) REFERENCES pets (id),
    CONSTRAINT ck_friend_request_self
        CHECK (requester_pet_id <> target_pet_id),
    CONSTRAINT ck_friend_request_status
        CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELED', 'EXPIRED'))
);

CREATE UNIQUE INDEX uk_friend_request_pending_pair
    ON friend_requests (pair_low_id, pair_high_id)
    WHERE status = 'PENDING';

CREATE INDEX ix_friend_request_pending_requester_target_expires
    ON friend_requests (requester_pet_id, target_pet_id, expires_at)
    WHERE status = 'PENDING';

CREATE INDEX ix_friend_request_pending_target_requester_expires
    ON friend_requests (target_pet_id, requester_pet_id, expires_at)
    WHERE status = 'PENDING';

CREATE TABLE friendships (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_low_id   BIGINT      NOT NULL,
    pet_high_id  BIGINT      NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_friendships_pet_low
        FOREIGN KEY (pet_low_id) REFERENCES pets (id),
    CONSTRAINT fk_friendships_pet_high
        FOREIGN KEY (pet_high_id) REFERENCES pets (id),
    CONSTRAINT ck_friendship_pair
        CHECK (pet_low_id < pet_high_id),
    CONSTRAINT uk_friendship_pair
        UNIQUE (pet_low_id, pet_high_id)
);

CREATE INDEX ix_friendship_pet_high_low
    ON friendships (pet_high_id, pet_low_id);
